### ISSUE TITLE
Firefox: UI Bug List

### ISSUE THREAD

**Issue by anjj123** [GetSpeckle/speckle-browser-extension#68]
Forefox has some weird UI bugs that aren't present on the chrome extension

1. ~Account Drop down menu causes the background to turn white~ Partially fixed. Name turns into a grey box now, and background still turns white if Account Name is too long
![Screen Shot 2019-05-12 at 2 49 31 pm](https://user-images.githubusercontent.com/39804936/57579038-a1a23c00-74d9-11e9-9c5a-a837ebaf5e71.png)

~2. If the account name is too long it causes UI bugs in the account dropdown, such as scroll bar disappearing and create/import moving to the right-hand-side (solution, and this was recommended in another issue: character limit on account names)~

**Comment by mytechtip** [comment]
It appears the white background while hovering over the dropdown is caused by the semantic UI buttons on the dropdown. Will do more investigation to work around it.

**Comment by mytechtip** [comment]
The fix is not perfect as now the colour for the current account becomes gray when the drop down is hovered over. This is the best I can do so far.

**Comment by anjj123** [comment]
Ill drop this down to low priority for now. There are other oddities, such as the background turning white again if the Account Name is too long. We need to enforce max characters for account names.

![Screen Shot 2019-05-09 at 9 56 24 pm](https://user-images.githubusercontent.com/39804936/57679003-aef02f80-766d-11e9-86ce-06d91c0952e1.png)

**Comment by fyang1024** [comment]
@anjj123 the gray background issue is fixed now. Also account name is restricted to 32 chars. Long existing names will be shortened to display. Please test it and close it if they are ok.

**Comment by anjj123** [comment]
@fyang1024 issue is still live for me. It may be related to the character limit. Maybe try reducing it to 28 chars and see if it fixes.Also, even at 32 chars its still causing bugs if user uses all numbers or caps only 

![Screen Shot 2019-05-14 at 10 25 05 pm](https://user-images.githubusercontent.com/39804936/57697642-179fd200-7697-11e9-86d8-71f7c34377e5.png)

**Comment by fyang1024** [comment]
@anjj123 I didn't change the 32 chars limit, as I am afraid users may complain it's too restricted. Instead I display a shortened name if it's over 28 chars.

**Comment by anjj123** [comment]
@fyang1024 I agree with your change. It looks much better but the bug still persists on firefox. Character limit isn't the issue. 

![Screen Shot 2019-05-14 at 10 42 56 pm](https://user-images.githubusercontent.com/39804936/57698796-c6dda880-7699-11e9-8ccc-95032bd7e960.png)
